schema: "**/*.graphqls"
schemaEntrypoint: "src/graphql/type-defs.graphqls"
documents: "**/*.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - typescript-resolvers
cacheDir: __generated__
